baseURL = 'https://girlpile.org/'
languageCode = 'en-us'
title = 'Live Kiersted - WORK'
theme = 'hugo-scroll'
disableKinds = ["section", "taxonomy", "term", "RSS", "robotsTXT"]
defaultContentLanguage = "en"
ignoreFiles = [ ".*/README.md" ]

[params]
    favicon = "favicon.png"
    hidedesignbyline = true
    title = "Live Kiersted"
    description = "WORK"
    images = ["favicon.png"]
[markup.goldmark.renderer]
  unsafe = true # Allow HTML in md files