name: Initialize Submodules

on:
  push:
    branches:
      - main

jobs:
  initialize-submodules:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Initialize and update submodules
        run: |
          git submodule init
          git submodule update

      - name: Commit submodule references
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Initialize submodules"
          git push origin main